### ISSUE TITLE
Argument 1 of AudioContext.constructor '[object Object]' is not a valid value for enumeration AudioChannel.

### ISSUE THREAD

**Issue by meet0929** [chrisguttandin/angular-audio-context#420] opened 2019-09-11 12:45 UTC
showing error in the mozilla firefox.

**Comment by chrisguttandin** [comment] 2019-09-11 13:03
Hi @meet0929,

unfortunately I can't reproduce the error. Is your project publicly available? Which version of Firefox are you using?

**Comment by meet0929** [comment] 2019-09-11 13:14
its version of 46.0.1(x64 en us). sorry to say its on local env

**Comment by meet0929** [comment] 2019-09-13 14:52
i have updated my browser and its not showing error in the firefox. another issue i found with my raw url, its does not play sound in firefox and showing icon in the tab.converting the arraybuffer to audio buffer by this code
[const myArrayBuffer = audioCtx.createBuffer(2, audioCtx.sampleRate * 2, audioCtx.sampleRate);
        myArrayBuffer.copyToChannel(buffer, 0);

**Comment by chrisguttandin** [comment] 2019-09-13 15:29
Hi @meet0929,

can you please post a larger snippet of the code that is not working? It's hard to tell what's causing the problem by the code that you posted so far.

Does it work in other browsers?

**Comment by meet0929** [comment] 2019-09-13 16:27
const xmlHttp = new XMLHttpRequest();

      xmlHttp.open('GET', alertAudioEndpoint, true); // false for synchronous request
      xmlHttp.responseType = 'arraybuffer';
      xmlHttp.setRequestHeader('Authorization', 'Bearer ' + token);

      xmlHttp.onload = (oEvent) => {

        if (xmlHttp.status === 404) {
          console.log('Audio wasn\'t found');
          return resolve();
        }
const buffer = new Float32Array(xmlHttp.response);
const out = this._audioContext.audio.createBuffer(1, 16384, 16000);
        out.copyToChannel(buffer, 0);
        return resolve(out);
      };
 xmlHttp.send(null);

const bufferSourceNode = this.audioContext.audio.createBufferSource();
    // bufferSourceNode.channelCount = 1;
    // bufferSourceNode.channelCountMode
    console.log('Created buffer source node');
    //set buffer to one of the loaded sounds;
    bufferSourceNode.buffer = sound;
    //connect to output
    bufferSourceNode.connect(this.audioContext.audio.destination);
    //play the sound
    bufferSourceNode.start();
    //loading stop
    this.isLoading = false;
    //check sound playing
    this.isPlaySound = true;
    //stop the sound
    // bufferSourceNode.stop(this.audioContext.currentTime + 0.5);
    //end  the sound
    bufferSourceNode.onended = () => {
      this.isPlaySound = false;
      this.isEnded = true;
    }

**Comment by meet0929** [comment] 2019-09-13 16:28
yes its working in crome

**Comment by chrisguttandin** [comment] 2019-09-13 16:38
Thank you.

I wonder why you sometimes use `this._audioContext` and sometimes you use it without the underscore like this `this.audioContext`. Is this a typo or do you have two different properties?

I also don't really know what `this._audioContext.audio` is. Can you please explain that to me or show me how you assign it?

I noticed that you don't decode the file that you are loading anywhere. Is it the raw audio data or is it encoded as MP3 or OGG.

**Comment by meet0929** [comment] 2019-09-13 16:44
understood about, i try some different way also and its and also try the library and follow the documentation. it is the raw audio data and try to convert the decode its giving error
by using BaseAudioContext.decodeAudioData()

**Comment by meet0929** [comment] 2019-09-13 17:29
![image](https://user-images.githubusercontent.com/30224694/64882143-206ed780-d67a-11e9-8657-eda90ca09fd2.png)

**Comment by chrisguttandin** [comment] 2019-10-04 16:47
Hi @meet0929, I wonder if you were able to get it working in the meantime or if you have some updated code I could use to reproduce the error?

**Comment by chrisguttandin** [comment] 2020-02-26 13:10
I'm closing this now due to inactivity. Please feel to open a new issue if you run into any other issue.

**Closed by chrisguttandin** 2020-02-26 13:10 UTC
